### ISSUE TITLE
[FEATURE] 회원가입 API

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-be#1]
## 🌴 작업 브랜치 
`feature/#1`

## 💼 TASK 개요 
[POST] /api/v1/users/

## ✅ TODO 및 진행현황 
- [ ] json 유저데이터 세팅
- [ ] 회원가입 로직 구현
- [ ] 에러 처리 구현
