### ISSUE TITLE
[FEATURE] 게시글 조회 API

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-be#15]
## 🌴 작업 브랜치 
`feature/#15`

## 💼 TASK 개요 
[GET] api/v1/boards?offset={}&limit={}

## ✅ TODO 및 진행현황 

- [ ] 인피니트 스크롤링을 위한 페이지
- [ ] 게시글 조회 로직 추가
- [ ] 오류 처리 추가
