### ISSUE TITLE
[BUG] 댓글 추가, 좋아요 추가시 좋아요 증가 현상 해결

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-be#46]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요
- 댓글 추가 및 좋아요 추가와 같은 특정 게시글 조회가 일어나는 JSON 조회 로직에 좋아요 추가 로직이 포함되어있어서 문제가 발생
- 로직을 따로 분리해야 함

## TODO

- [x] 게시글 조회 목적에 따른 로직 분리 필요
