### ISSUE TITLE
[BUG] Pool 연결 누수 문제 해결

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-be#53]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- connection 할당받은 뒤, release 과정 추가
- Pool 연결 제한 수를 넘기면 발생하는 문제 방지

## TODO

- [ ] 모든 컨트롤러 finally 과정을 추가하여 연결받은 connection 해제하는 과정 추가
