### ISSUE TITLE
[BUG] Pool Connection 연결 제한 문제

### ISSUE THREAD

**Issue by choiyoorim** [100-hours-a-week/2-stella-choi-community-be#59]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 연결 제한 형태 변경
- release 제대로 되고있는지 확인 필요

## TODO

- [ ] connection 해제 과정 추가
